# Generated by Django 2.1.15 on 2020-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg_responsavel',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
