# Generated by Django 2.1.7 on 2020-04-24 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='Procedimento',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='lif',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='paciente',
        ),
        migrations.RenameField(
            model_name='atendimentos',
            old_name='Procedimento',
            new_name='procedimento',
        ),
        migrations.DeleteModel(
            name='Atendimento',
        ),
    ]
