# Generated by Django 2.1.7 on 2020-04-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200425_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimentos',
            old_name='protocolo',
            new_name='codigo_lif',
        ),
    ]
