# Generated by Django 2.1.7 on 2020-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200425_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='bera',
            name='direito_picos_inter_latencias_I',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_inter_latencias_III',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_inter_latencias_III_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_inter_latencias_I_III',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_inter_latencias_I_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_inter_latencias_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_inter_latencias_interpicos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_latencia_abosoluta_I',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_latencia_abosoluta_III',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_latencia_abosoluta_III_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_latencia_abosoluta_I_III',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_latencia_abosoluta_I_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_latencia_abosoluta_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='direito_picos_latencia_abosoluta_interpicos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_inter_latencias_I',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_inter_latencias_III',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_inter_latencias_III_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_inter_latencias_I_III',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_inter_latencias_I_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_inter_latencias_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_inter_latencias_interpicos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_latencia_abosoluta_I',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_latencia_abosoluta_III',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_latencia_abosoluta_III_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_latencia_abosoluta_I_III',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_latencia_abosoluta_I_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_latencia_abosoluta_V',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bera',
            name='esquerdo_picos_latencia_abosoluta_interpicos',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
