# Generated by Django 2.1.7 on 2020-05-08 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200508_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquerdo_picos_P300', models.CharField(max_length=10)),
                ('esquerdo_picos_P1', models.CharField(blank=True, max_length=10)),
                ('esquerdo_picos_N1', models.CharField(blank=True, max_length=10)),
                ('esquerdo_picos_P2', models.CharField(blank=True, max_length=10)),
                ('esquerdo_picos_N2', models.CharField(blank=True, max_length=10)),
                ('direito_picos_P300', models.CharField(max_length=10)),
                ('direito_picos_P1', models.CharField(blank=True, max_length=10)),
                ('direito_picos_N1', models.CharField(blank=True, max_length=10)),
                ('direito_picos_P2', models.CharField(blank=True, max_length=10)),
                ('direito_picos_N2', models.CharField(blank=True, max_length=10)),
                ('evolucao', models.TextField()),
                ('conclusao_exame', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Consulta')),
            ],
        ),
    ]
