# Generated by Django 2.1.7 on 2020-05-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_audiometria'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiometria',
            name='direito_compilancia_200',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_compilancia_estatica',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_maximo_relax',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_pressao',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_compilancia_200',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_compilancia_estatica',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_maximo_relax',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_pressao',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
