# Generated by Django 2.1.7 on 2020-05-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200508_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_1000_contra_oe',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_1000_diferenca',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_1000_ipsi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_1000_limiar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_2000_contra_oe',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_2000_diferenca',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_2000_ipsi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_2000_limiar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_4000_contra_oe',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_4000_diferenca',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_4000_ipsi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_4000_limiar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_500_contra_oe',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_500_diferenca',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_500_ipsi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_reflexo_frequencia_500_limiar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='direito_timpanometria',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_1000_contra_od',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_1000_diferenca',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_1000_ipsi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_1000_limiar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_2000_contra_od',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_2000_diferenca',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_2000_ipsi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_2000_limiar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_4000_contra_od',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_4000_diferenca',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_4000_ipsi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_4000_limiar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_500_contra_od',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_500_diferenca',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_500_ipsi',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_reflexo_frequencia_500_limiar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='audiometria',
            name='esquerdo_timpanometria',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
