# Generated by Django 2.1.7 on 2020-05-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200508_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiometria',
            old_name='direito_reflexo_frequencia_1000_contra_oe',
            new_name='direito_reflexo_frequencia_1000_contra',
        ),
        migrations.RenameField(
            model_name='audiometria',
            old_name='direito_reflexo_frequencia_2000_contra_oe',
            new_name='direito_reflexo_frequencia_2000_contra',
        ),
        migrations.RenameField(
            model_name='audiometria',
            old_name='direito_reflexo_frequencia_4000_contra_oe',
            new_name='direito_reflexo_frequencia_4000_contra',
        ),
        migrations.RenameField(
            model_name='audiometria',
            old_name='direito_reflexo_frequencia_500_contra_oe',
            new_name='direito_reflexo_frequencia_500_contra',
        ),
        migrations.RenameField(
            model_name='audiometria',
            old_name='esquerdo_reflexo_frequencia_1000_contra_od',
            new_name='esquerdo_reflexo_frequencia_1000_contra',
        ),
        migrations.RenameField(
            model_name='audiometria',
            old_name='esquerdo_reflexo_frequencia_2000_contra_od',
            new_name='esquerdo_reflexo_frequencia_2000_contra',
        ),
        migrations.RenameField(
            model_name='audiometria',
            old_name='esquerdo_reflexo_frequencia_4000_contra_od',
            new_name='esquerdo_reflexo_frequencia_4000_contra',
        ),
        migrations.RenameField(
            model_name='audiometria',
            old_name='esquerdo_reflexo_frequencia_500_contra_od',
            new_name='esquerdo_reflexo_frequencia_500_contra',
        ),
    ]
