# Generated by Django 2.1.7 on 2020-05-10 17:51

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('app', '0010_auto_20200508_2315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atendimentos',
            new_name='Atendimento',
        ),
    ]
