# Generated by Django 2.1.7 on 2020-05-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200510_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audiometria',
            new_name='ResultadoAudiometria',
        ),
        migrations.RenameModel(
            old_name='Bera',
            new_name='ResultadoBera',
        ),
        migrations.RenameModel(
            old_name='Pac',
            new_name='ResultadoPac',
        ),
        migrations.RenameModel(
            old_name='LaudoPadrao',
            new_name='ResultadoPadrao',
        ),
    ]
