# Generated by Django 2.1.7 on 2020-05-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200510_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='cid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
