# Generated by Django 2.1.7 on 2020-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_procedimento_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='cid',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
