# Generated by Django 2.1.7 on 2020-05-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200510_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='cid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoaudiometria',
            name='conclusao_exame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoaudiometria',
            name='evolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadobera',
            name='conclusao_exame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadobera',
            name='evolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadopac',
            name='conclusao_exame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadopac',
            name='evolucao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadopadrao',
            name='conclusao_exame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadopadrao',
            name='evolucao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
