# Generated by Django 2.1.7 on 2020-05-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200511_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
