# Generated by Django 2.1.7 on 2020-05-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200511_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadobera',
            old_name='direito_picos_latencia_abosoluta_I',
            new_name='direito_picos_latencia_absoluta_I',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='direito_picos_latencia_abosoluta_III',
            new_name='direito_picos_latencia_absoluta_III',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='direito_picos_latencia_abosoluta_III_V',
            new_name='direito_picos_latencia_absoluta_III_V',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='direito_picos_latencia_abosoluta_I_III',
            new_name='direito_picos_latencia_absoluta_I_III',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='direito_picos_latencia_abosoluta_I_V',
            new_name='direito_picos_latencia_absoluta_I_V',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='direito_picos_latencia_abosoluta_V',
            new_name='direito_picos_latencia_absoluta_V',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='direito_picos_latencia_abosoluta_interpicos',
            new_name='direito_picos_latencia_absoluta_interpicos',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='esquerdo_picos_latencia_abosoluta_I',
            new_name='esquerdo_picos_latencia_absoluta_I',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='esquerdo_picos_latencia_abosoluta_III',
            new_name='esquerdo_picos_latencia_absoluta_III',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='esquerdo_picos_latencia_abosoluta_III_V',
            new_name='esquerdo_picos_latencia_absoluta_III_V',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='esquerdo_picos_latencia_abosoluta_I_III',
            new_name='esquerdo_picos_latencia_absoluta_I_III',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='esquerdo_picos_latencia_abosoluta_I_V',
            new_name='esquerdo_picos_latencia_absoluta_I_V',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='esquerdo_picos_latencia_abosoluta_V',
            new_name='esquerdo_picos_latencia_absoluta_V',
        ),
        migrations.RenameField(
            model_name='resultadobera',
            old_name='esquerdo_picos_latencia_abosoluta_interpicos',
            new_name='esquerdo_picos_latencia_absoluta_interpicos',
        ),
    ]
