# Generated by Django 2.1.7 on 2020-05-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_procedimento_tipo_resultado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimento',
            old_name='tipo_resultado',
            new_name='tipo_laudo',
        ),
    ]
