# Generated by Django 2.1.7 on 2020-05-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200512_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='tipo_laudo',
            field=models.CharField(choices=[['PADRAO', 'Padrão'], ['BERA', 'Bera'], ['PAC', 'Pac'], ['AUDIOMETRIA', 'Audiometria']], default='PADRAO', max_length=20),
        ),
    ]
