# Generated by Django 2.1.7 on 2020-05-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_lif_numero_lif_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lif',
            name='numero_lif_atual',
            field=models.IntegerField(default=0),
        ),
    ]
