# Generated by Django 2.1.7 on 2020-05-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200512_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lif',
            old_name='numero_lif_atual',
            new_name='codigo_lif_atual',
        ),
    ]
