# Generated by Django 2.1.15 on 2020-05-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200512_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='cid',
        ),
    ]
