# Generated by Django 2.1.15 on 2020-05-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_procedimento_cid'),
        ('app', '0024_auto_20200523_1943'),
    ]

    operations = [
    ]
